    name: Python Code Quality Check
    
    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]
    
    jobs:
      lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' # 确保这里的版本和您项目使用的一致
    
        - name: Install dependencies and linter
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
        - name: Lint with flake8
          run: |
            # 运行 flake8 来检查代码风格和错误。
            # --count: 显示总错误数
            # --show-source: 显示有问题的代码行
            # --statistics: 显示每个错误的统计
            flake8 . --count --show-source --statistics
